---
version: "3.5"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1001
      - PGID=100
      - TZ=America/Sao_Paulo
      - VERSION=docker
    volumes:
      - /opt/plex:/config
      - /srv/dev-disk-by-uuid-e53d5d99-1d0e-43b7-80b8-fc227ec518ee/Homelab/MEDIA_CENTER/Filmes:/data/movies
      - /srv/dev-disk-by-uuid-e53d5d99-1d0e-43b7-80b8-fc227ec518ee/Homelab/MEDIA_CENTER/Series:/data/tv 
#     - PATH-TO-ARCHIVES:/data/movies
    devices:
      - /dev/dri:/dev/dri 
    restart: unless-stopped
