---
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - VERSION=docker
    volumes:
      - /opt/plex:/config
      - /mnt/homelab-ssd-thor/MEDIA_CENTER/Filmes:/data/movies
      - /mnt/homelab-hd-externo-thor/MEDIA_CENTER/Series:/data/tv 
#     - PATH-TO-ARCHIVES:/data/movies
    devices:
      - /dev/dri:/dev/dri 
    restart: unless-stopped
