services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    volumes:
      - /home/antony/apps/jellyfin:/config
      - /mnt/media/MEDIA_CENTER/Series:/data/tvshows
      - /mnt/media/MEDIA_CENTER/Filmes:/data/movies
      - /mnt/media/MEDIA_CENTER/Videos:/data/videos
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    restart: unless-stopped