version: '3.5'

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional   
    volumes:
      - /opt/jellyfin:/config
      - PATH-TO-ARCHIVES:/data/tvshows
      - PATH-TO-ARCHIVES:/data/movies 
      - PATH-TO-ARCHIVES:/data/videos  
#    - /srv/dev-disk-by-uuid-e53d5d99-1d0e-43b7-80b8-fc227ec518ee/Homelab:/data/tvshows   
    environment:
      - PUID=1001
      - PGID=100
      - TZ=America/Sao_Paulo
#      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    devices:
      - /dev/dri:/dev/dri 
    restart: unless-stopped

