version: '3.8' 

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1001
      - PGID=100
      - TZ=America/Sao_Paulo
    volumes:
      - /opt/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1001
      - PGID=100
      - TZ=America/Sao_Paulo
    volumes:
      - /opt/radarr:/config
      - /srv/dev-disk-by-uuid-e53d5d99-1d0e-43b7-80b8-fc227ec518ee/Homelab/MEDIA_CENTER/Filmes:/movies 
      - /srv/dev-disk-by-uuid-e53d5d99-1d0e-43b7-80b8-fc227ec518ee/Homelab/MEDIA_CENTER/Downloads:/downloads 
    ports:
      - 7878:7878
    restart: unless-stopped
    
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=100
      - TZ=America/Sao_Paulo
    volumes:
      - /opt/sonarr:/config
      - /srv/dev-disk-by-uuid-e53d5d99-1d0e-43b7-80b8-fc227ec518ee/Homelab/MEDIA_CENTER/Series:/tv #optional
      - /srv/dev-disk-by-uuid-e53d5d99-1d0e-43b7-80b8-fc227ec518ee/Homelab/MEDIA_CENTER/Downloads:/downloads 
    ports:
      - 8989:8989
    restart: unless-stopped
    
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1001
      - PGID=100
      - TZ=America/Sao_Paulo
    volumes:
      - /opt/bazarr:/config
      - /srv/dev-disk-by-uuid-e53d5d99-1d0e-43b7-80b8-fc227ec518ee/Homelab/MEDIA_CENTER/Filmes:/movies #optional
      - /srv/dev-disk-by-uuid-e53d5d99-1d0e-43b7-80b8-fc227ec518ee/Homelab/MEDIA_CENTER/Series:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1001
      - PGID=100
      - TZ=America/Sao_Paulo
    volumes:
      - /opt/overseerr/config:/config
    ports:
      - 5055:5055
    restart: unless-stopped