services:
  traefik:
    image: traefik:v3
    container_name: traefik
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256m
    restart: unless-stopped
    networks:
      - traefik

    ports:
      - "80:80"
      - "443:443"

    environment:
      - ADGUARD_DOMAIN=${ADGUARD_DOMAIN}
      - ADGUARD_HOME_DOMAIN=${ADGUARD_HOME_DOMAIN}
      - ADGUARD_IP=${ADGUARD_IP}
      - ADGUARD_PORT=${ADGUARD_PORT}
      - ADGUARD_SECONDARY_DOMAIN=${ADGUARD_SECONDARY_DOMAIN}
      - ADGUARD_SECONDARY_HOME_DOMAIN=${ADGUARD_SECONDARY_HOME_DOMAIN}
      - ADGUARD_SECONDARY_IP=${ADGUARD_SECONDARY_IP}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
      - CLOUDFLARE_TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
      - HOMARR_DOMAIN=${HOMARR_DOMAIN}
      - HOMARR_HOME_DOMAIN=${HOMARR_HOME_DOMAIN}
      - PLEX_DOMAIN=${PLEX_DOMAIN}
      - PLEX_HOME_DOMAIN=${PLEX_HOME_DOMAIN}
      - PLEX_IP=${PLEX_IP}
      - PROXMOX_CLAIRE_DOMAIN=${PROXMOX_CLAIRE_DOMAIN}
      - PROXMOX_CLAIRE_HOME_DOMAIN=${PROXMOX_CLAIRE_HOME_DOMAIN}
      - PROXMOX_CLAIRE_IP=${PROXMOX_CLAIRE_IP}
      - PROXMOX_DOMAIN=${PROXMOX_DOMAIN}
      - PROXMOX_HOME_DOMAIN=${PROXMOX_HOME_DOMAIN}
      - PROXMOX_LEON_DOMAIN=${PROXMOX_LEON_DOMAIN}
      - PROXMOX_LEON_HOME_DOMAIN=${PROXMOX_LEON_HOME_DOMAIN}
      - PROXMOX_LEON_IP=${PROXMOX_LEON_IP}
      - SERVER_IP=${SERVER_IP}
      - TRAEFIK_BASIC_AUTH=${TRAEFIK_BASIC_AUTH}
      - TRAEFIK_DOMAIN=${TRAEFIK_DOMAIN}
      - TRAEFIK_LOCAL_DOMAIN=${TRAEFIK_LOCAL_DOMAIN}
      - UPSNAP_HOME_DOMAIN=${UPSNAP_HOME_DOMAIN}
      - UPSNAP_IP=${UPSNAP_IP}

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/antony/apps/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - /home/antony/apps/traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - /home/antony/apps/traefik/acme.json:/acme.json

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_DOMAIN}`) || Host(`${TRAEFIK_LOCAL_DOMAIN}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=auth@docker"
      - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_BASIC_AUTH}"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128m
    restart: unless-stopped
    command: tunnel --no-autoupdate --config /etc/cloudflared/config.yml run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    volumes:
      - /home/antony/apps/traefik/cloudflared-config.yml:/etc/cloudflared/config.yml:ro
    networks:
      - traefik

networks:
  traefik:
    external: true
