http:
  middlewares:
    redirect-https:
      redirectScheme:
        scheme: https
        permanent: true

  serversTransports:
    insecure:
      insecureSkipVerify: true

  routers:
    proxmox-leon:
      rule: "Host(`{{ env "PROXMOX_LEON_DOMAIN" }}`) || Host(`{{ env "PROXMOX_LEON_HOME_DOMAIN" }}`) || Host(`{{ env "PROXMOX_DOMAIN" }}`) || Host(`{{ env "PROXMOX_HOME_DOMAIN" }}`)"
      entrypoints: [websecure]
      tls:
        certResolver: cloudflare
      service: proxmox-leon

    proxmox-claire:
      rule: "Host(`{{ env "PROXMOX_CLAIRE_DOMAIN" }}`) || Host(`{{ env "PROXMOX_CLAIRE_HOME_DOMAIN" }}`)"
      entrypoints: [websecure]
      tls:
        certResolver: cloudflare
      service: proxmox-claire

    adguard:
      rule: "Host(`{{ env "ADGUARD_DOMAIN" }}`) || Host(`{{ env "ADGUARD_HOME_DOMAIN" }}`)"
      entrypoints: [websecure]
      tls:
        certResolver: cloudflare
      service: adguard

    adguard-secondary:
      rule: "Host(`{{ env "ADGUARD_SECONDARY_DOMAIN" }}`) || Host(`{{ env "ADGUARD_SECONDARY_HOME_DOMAIN" }}`)"
      entrypoints: [websecure]
      tls:
        certResolver: cloudflare
      service: adguard-secondary

    plex:
      rule: "Host(`{{ env "PLEX_HOME_DOMAIN" }}`)"
      entrypoints: [websecure]
      tls:
        certResolver: cloudflare
      service: plex


  services:
    proxmox-leon:
      loadBalancer:
        serversTransport: insecure
        servers:
          - url: "https://{{ env "PROXMOX_LEON_IP" }}:8006"

    proxmox-claire:
      loadBalancer:
        serversTransport: insecure
        servers:
          - url: "https://{{ env "PROXMOX_CLAIRE_IP" }}:8006"

    adguard:
      loadBalancer:
        servers:
          - url: "http://{{ env "ADGUARD_IP" }}:{{ env "ADGUARD_PORT" }}"

    adguard-secondary:
      loadBalancer:
        servers:
          - url: "http://{{ env "ADGUARD_SECONDARY_IP" }}:{{ env "ADGUARD_PORT" }}"

    plex:
      loadBalancer:
        servers:
          - url: "http://{{ env "PLEX_IP" }}:32400"
