services:
  filebrowser:
    image: filebrowser/filebrowser:v2.63.5
    container_name: filebrowser
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128m
    user: "1000:1000"
    networks:
      - traefik
    ports:
      - "8181:80"
    volumes:
      - /home/antony:/srv
      - /mnt:/srv/mnt
      - /home/antony/apps/filebrowser:/config
      - /home/antony/apps/filebrowser/db:/database
    environment:
      - TZ=America/Sao_Paulo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.rule=Host(`${FILEBROWSER_DOMAIN}`) || Host(`${FILEBROWSER_HOME_DOMAIN}`)"
      - "traefik.http.routers.filebrowser.entrypoints=websecure"
      - "traefik.http.routers.filebrowser.tls=true"
      - "traefik.http.routers.filebrowser.tls.certresolver=cloudflare"
      - "traefik.http.services.filebrowser.loadbalancer.server.port=80"
    restart: unless-stopped

networks:
  traefik:
    external: true