services:
  adguardhome-sync:
    image: ghcr.io/bakito/adguardhome-sync:latest
    container_name: adguardhome-sync
    restart: unless-stopped
    volumes:
      - /home/antony/apps/adguardhome-sync/adguardhome-sync.yaml:/root/.adguardhome-sync.yaml:ro
