---
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512m
    hostname: syncthing
    networks:
      - traefik
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /home/antony/apps/syncthing/config:/config
      - /mnt/homelab-hd-interno/SYNCTHING:/sync
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syncthing.rule=Host(`${SYNCTHING_DOMAIN}`) || Host(`${SYNCTHING_HOME_DOMAIN}`)"
      - "traefik.http.routers.syncthing.entrypoints=websecure"
      - "traefik.http.routers.syncthing.tls=true"
      - "traefik.http.routers.syncthing.tls.certresolver=cloudflare"
      - "traefik.http.services.syncthing.loadbalancer.server.port=8384"
    restart: unless-stopped

networks:
  traefik:
    external: true
