global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'netdata'
    metrics_path: '/api/v1/allmetrics'
    params:
      format: ['prometheus_all_hosts']
    honor_labels: true
    static_configs:
      - targets: ['netdata:19999']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['192.168.3.110:9100']
